-- Generated by scripts/generate-seed.ts from src/data. Do not edit by hand.

insert into partners (id, name, kind) values
  ('demo-newcomer-society', 'Demo Newcomer Society', 'community'),
  ('demo-credit-union', 'Demo Credit Union', 'financial')
on conflict (id) do update set name = excluded.name, kind = excluded.kind;

insert into directory_entries (id, organization, aliases, category, phone, url, guidance) values
  ('ircc', 'Immigration, Refugees and Citizenship Canada (IRCC)', array['ircc', 'immigration canada', 'immigration refugees and citizenship', 'citizenship and immigration', 'cic', 'immigration department', 'immigration office']::text[], 'government', '1-888-242-2100', 'https://www.canada.ca/en/immigration-refugees-citizenship/corporate/contact-ircc.html', 'IRCC never threatens arrest or deportation and never asks for payment by gift card or crypto.'),
  ('cra', 'Canada Revenue Agency (CRA)', array['cra', 'canada revenue agency', 'revenue canada', 'tax agency', 'revenue agency']::text[], 'government', '1-800-959-8281', 'https://www.canada.ca/en/revenue-agency/corporate/contact-information.html', 'The CRA never demands immediate payment by gift card, prepaid card or cryptocurrency.'),
  ('cbsa', 'Canada Border Services Agency (CBSA)', array['cbsa', 'canada border services', 'border services', 'border agency', 'customs']::text[], 'government', '1-800-461-9999', 'https://www.cbsa-asfc.gc.ca/contact/bis-sif-eng.html', 'The CBSA does not call to demand fines or threaten arrest over the phone.'),
  ('service-canada', 'Service Canada', array['service canada', 'social insurance', 'sin number']::text[], 'government', '1-800-622-6232', 'https://www.canada.ca/en/employment-social-development/corporate/contact.html', 'Service Canada will not say your SIN is suspended or ask you to move money to protect it.'),
  ('police', 'Police (RCMP or local)', array['rcmp', 'police', 'royal canadian mounted police', 'officer', 'constable']::text[], 'government', null, 'https://www.rcmp-grc.gc.ca/en/contact-us', 'Police do not take payment over the phone to cancel a warrant. Call your local non-emergency line.'),
  ('rbc', 'RBC Royal Bank', array['rbc', 'royal bank']::text[], 'bank', null, 'https://www.rbc.com', 'Call the number on the back of your card. Your bank will never ask for a one-time code.'),
  ('td', 'TD Bank', array['td', 'td bank', 'toronto dominion']::text[], 'bank', null, 'https://www.td.com', 'Call the number on the back of your card. Your bank will never ask for a one-time code.'),
  ('scotiabank', 'Scotiabank', array['scotiabank', 'scotia']::text[], 'bank', null, 'https://www.scotiabank.com', 'Call the number on the back of your card. Your bank will never ask for a one-time code.'),
  ('bmo', 'BMO Bank of Montreal', array['bmo', 'bank of montreal']::text[], 'bank', null, 'https://www.bmo.com', 'Call the number on the back of your card. Your bank will never ask for a one-time code.'),
  ('cibc', 'CIBC', array['cibc', 'canadian imperial bank']::text[], 'bank', null, 'https://www.cibc.com', 'Call the number on the back of your card. Your bank will never ask for a one-time code.'),
  ('demo-credit-union', 'Demo Credit Union', array['demo credit union', 'credit union']::text[], 'bank', null, 'https://example.org', 'Call the number on the back of your card. Your credit union will never ask for a one-time code.'),
  ('cafc', 'Canadian Anti-Fraud Centre', array['anti-fraud centre', 'anti fraud centre', 'cafc']::text[], 'reporting', '1-888-495-8501', 'https://antifraudcentre-centreantifraude.ca/report-signalez-eng.htm', 'Report scam calls here, even if you did not lose money.')
on conflict (id) do update set
  organization = excluded.organization,
  aliases = excluded.aliases,
  category = excluded.category,
  phone = excluded.phone,
  url = excluded.url,
  guidance = excluded.guidance;
