import { writeFileSync } from "node:fs";
import { DIRECTORY } from "../src/data/directory";
import { PARTNERS } from "../src/data/partners";

const literal = (value: string | null) =>
  value === null ? "null" : `'${value.replaceAll("'", "''")}'`;
const textArray = (values: string[]) => `array[${values.map(literal).join(", ")}]::text[]`;

const partnerRows = PARTNERS.map(
  (p) => `  (${literal(p.id)}, ${literal(p.name)}, ${literal(p.kind)})`,
).join(",\n");

const directoryRows = DIRECTORY.map(
  (d) =>
    `  (${[literal(d.id), literal(d.organization), textArray(d.aliases), literal(d.category), literal(d.phone), literal(d.url), literal(d.guidance)].join(", ")})`,
).join(",\n");

const sql = `-- Generated by scripts/generate-seed.ts from src/data. Do not edit by hand.

insert into partners (id, name, kind) values
${partnerRows}
on conflict (id) do update set name = excluded.name, kind = excluded.kind;

insert into directory_entries (id, organization, aliases, category, phone, url, guidance) values
${directoryRows}
on conflict (id) do update set
  organization = excluded.organization,
  aliases = excluded.aliases,
  category = excluded.category,
  phone = excluded.phone,
  url = excluded.url,
  guidance = excluded.guidance;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(
  `Wrote supabase/seed.sql (${PARTNERS.length} partners, ${DIRECTORY.length} directory entries)`,
);
